dist: xenial
sudo: required
language: node_js

node_js:
  - "16"

services:
  - docker

before_install:
  - docker build -t vashenko49/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vashenko49/react-test yarn run test

after_success:
  - docker build -t vashenko49/multi-client ./client
  - docker build -t vashenko49/multi-nginx ./nginx
  - docker build -t vashenko49/multi-server ./server
  - docker build -t vashenko49/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vashenko49/multi-client
  - docker push vashenko49/multi-nginx
  - docker push vashenko49/multi-server
  - docker push vashenko49/multi-worker

